"""Builds the anomaly-interpretation prompt.

Only actual telemetry/anomaly evidence goes into the prompt - the feature values embedded below
are read directly from the AnomalyResult/FeatureVector that already went through the Isolation
Forest, never invented. The instruction text explicitly tells the model not to reference any
metric not listed, and to answer only from the given evidence.
"""
from __future__ import annotations

import json

from ..anomaly.models import AnomalyResult

INTERPRETATION_SCHEMA_DESCRIPTION = """{
  "abnormal_summary": "<one or two sentences describing what looks abnormal>",
  "affected_service": "<the service name from the evidence below>",
  "significant_metrics": ["<metric names from the evidence below that appear most abnormal>"],
  "evidence": "<which specific values from the evidence below support this>",
  "confidence": "<low, medium, or high>"
}"""


def build_interpretation_prompt(anomaly_result: AnomalyResult) -> str:
    evidence = {
        "service": anomaly_result.service,
        "timestamp": anomaly_result.timestamp,
        "anomaly_score": anomaly_result.anomaly_score,
        "threshold": anomaly_result.threshold,
        "feature_values": anomaly_result.relevant_feature_values,
    }
    evidence_json = json.dumps(evidence, indent=2)

    return f"""You are helping an AIOps monitoring system interpret an anomaly detected by a
statistical model (Isolation Forest) running against a microservices payment platform.

An anomaly was flagged for the service and metrics below. This is the ONLY evidence available -
do not reference, assume, or invent any metric, service, or fact not present in this evidence.

Evidence:
{evidence_json}

Respond with ONLY a single JSON object matching exactly this shape (no extra text, no markdown
fences):
{INTERPRETATION_SCHEMA_DESCRIPTION}

Rules:
- "affected_service" must be exactly "{anomaly_result.service}" (the service this evidence is about).
- "significant_metrics" must only contain metric names that appear in "feature_values" above.
- Base "evidence" only on the numeric values shown above - do not fabricate numbers.
- If the evidence is too limited to say anything specific, say so plainly in "abnormal_summary"
  and set "confidence" to "low"."""


RCA_REASONING_SCHEMA_DESCRIPTION = """{
  "observed_evidence": "<factual restatement of the metric values and any retrieved incidents provided below - no interpretation>",
  "inference": "<what those facts suggest about the root cause, clearly marked as inference, not fact>"
}"""


def build_rca_reasoning_prompt(
    suspected_fault_type: str | None,
    suspected_root_cause_service: str,
    symptom_service: str,
    metric_anomalies: list[dict],
    retrieved_incidents: list[dict],
) -> str:
    """Asks the LLM only to *narrate* an RCA conclusion that deterministic logic
    (rca/signatures.py) already reached - never to decide the root cause itself. The prompt
    deliberately has no "recommendation" field: remediation proposals in this project are always
    generated by deterministic logic (remediation/proposer.py), never by the LLM - see that
    module's docstring."""
    evidence = {
        "suspected_fault_type": suspected_fault_type,
        "suspected_root_cause_service": suspected_root_cause_service,
        "symptom_service": symptom_service,
        "metric_anomalies": metric_anomalies,
        "retrieved_similar_incidents": retrieved_incidents,
    }
    evidence_json = json.dumps(evidence, indent=2)

    return f"""You are helping an AIOps monitoring system explain a root-cause analysis conclusion
that a deterministic statistical/rule-based system has ALREADY reached for a microservices payment
platform. Your job is only to narrate and explain this evidence in plain English - you are NOT
being asked to determine the root cause yourself, and you must NOT propose a different root cause
or any remediation action.

This is the complete evidence available. Do not reference, assume, or invent any metric,
service, incident, or fact not present here:
{evidence_json}

Respond with ONLY a single JSON object matching exactly this shape (no extra text, no markdown
fences):
{RCA_REASONING_SCHEMA_DESCRIPTION}

Rules:
- "observed_evidence" must restate only the facts given above (metric values, retrieved incident
  IDs/fault types) - no speculation.
- "inference" may reason about what those facts suggest, but must stay grounded in them and must
  explicitly note if the evidence is limited or ambiguous.
- Do not include a recommendation, remediation action, or Kubernetes/operational instruction of
  any kind - that is out of scope for this response."""
